### ISSUE TITLE
enlighten cant get length of a iterable (since they are potentially infinite)

### ISSUE THREAD

**Issue by merc1031** [neckbeard-io/kintro#30]
```
docker [analyze-issue-25] docker run --rm -it --user 1000 -v/media/innangard/TV:/data -v/media/innangard/TV:/media/innangard/TV merc1031/kintro:2022-01-06-1 --log-level debug server --url <REDACTED> --token <REDACTED> sync --find-path "/tv" --replace-path "/media/innangard/TV" --libtype show --filter-json '{"title==": "Cowboy Bebop (2021)"}' --max-workers 2 --worker-batch-size 2
2022-01-07 00:57:13 connect.py      server               MainThread              INFO    Connecting to plex via url(<REDACTED>) and token
2022-01-07 00:57:13 plex.py         sync                 MainThread              INFO    Starting sync process
Traceback (most recent call last):
  File "/usr/local/bin/kintro", line 33, in <module>
    sys.exit(load_entry_point('kintro', 'console_scripts', 'kintro')())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/kintro/kintro/plex.py", line 151, in sync
    pbar = manager.counter(total=len(tv), desc="episodes:", unit="episodes", color="green")
TypeError: object of type 'itertools.chain' has no len()
```

**Comment by merc1031** [comment]
I caused this. return type of the 2 branches was disjoint (iterable chain of Episode on shows, list of Episodes on episodes)
